local lush = require("lush")
local hsl = lush.hsl

local L0_base = hsl(45, 22, 93)
local L1_surface = hsl(210, 65, 45)
local L2_support = hsl(220, 45, 28)
local L3_accent = hsl(45, 90, 55)
local L4_energy = hsl(349, 93, 54)

local bg = L0_base
local fg = L2_support

return lush(function()
  return {
    ------------------------------------------------------------------
    -- Core / UI
    ------------------------------------------------------------------
    Normal         { fg = fg, bg = bg },
    NormalFloat    { fg = fg, bg = bg },
    FloatBorder    { fg = bg, bg = bg },
    Cursor         { fg = bg, bg = L1_surface },
    CursorIM       { fg = bg, bg = L1_surface },
    CursorColumn   { bg = bg.da(3) },
    CursorLine     { bg = bg.da(3) },
    ColorColumn    { bg = bg.da(5) },
    Conceal        { fg = L2_support.li(30) },
    CurSearch      { bg = L3_accent.li(20) },
    lCursor        { fg = bg, bg = L1_surface },
    Directory      { fg = L3_accent },
    DiffAdd        { fg = L3_accent },
    DiffChange     { fg = L1_surface },
    DiffDelete     { fg = L4_energy },
    DiffText       { bg = L3_accent.li(20) },
    EndOfBuffer    { fg = L2_support.li(25) },
    TermCursor     { fg = bg, bg = L1_surface },
    TermCursorNC   { fg = fg, bg = bg },
    ErrorMsg       { fg = L4_energy, gui = "bold" },
    VertSplit      { fg = L2_support.li(10) },
    Folded         { fg = L2_support.li(20), bg = bg.da(5) },
    FoldColumn     { fg = L2_support.li(10) },
    SignColumn     { fg = L2_support.li(15) },
    IncSearch      { fg = bg, bg = L3_accent },
    Substitute     { bg = L3_accent.li(30) },
    LineNr         { fg = L2_support.li(18) },
    LineNrAbove    { fg = L2_support.li(15) },
    LineNrBelow    { fg = L2_support.li(15) },
    CursorLineNr   { fg = L3_accent, gui = "bold" },
    CursorLineFold { fg = L2_support.li(10) },
    CursorLineSign { fg = L2_support.li(10) },
    MatchParen     { fg = bg, bg = L4_energy.li(20), gui = "bold" },
    ModeMsg        { fg = L3_accent, gui = "bold" },
    MsgArea        { fg = fg, bg = bg },
    MsgSeparator   { fg = L2_support.li(15) },
    MoreMsg        { fg = L3_accent },
    NonText        { fg = L2_support.li(20) },
    NormalNC       { fg = fg, bg = bg },
    Pmenu          { fg = bg.da(15), bg = L1_surface.li(10) },
    PmenuSel       { fg = bg, bg = L3_accent },
    PmenuKind      { fg = L2_support },
    PmenuKindSel   { fg = L0_base, bg = L3_accent },
    PmenuExtra     { fg = L2_support.li(10) },
    PmenuExtraSel  { fg = L0_base, bg = L3_accent.li(10) },
    PmenuSbar      { bg = bg.da(5) },
    PmenuThumb     { bg = L1_surface },
    Question       { fg = L3_accent },
    QuickFixLine   { bg = L0_base.da(5), fg = L3_accent },
    Search         { fg = bg, bg = L4_energy },
    SpecialKey     { fg = L2_support.li(30) },
    SpellBad       { sp = L4_energy, gui = "undercurl" },
    SpellCap       { sp = L3_accent, gui = "undercurl" },
    SpellLocal     { sp = L2_support.li(25), gui = "undercurl" },
    SpellRare      { sp = L1_surface, gui = "undercurl" },
    StatusLine     { fg = bg.da(20), bg = L1_surface },
    StatusLineNC   { fg = L2_support, bg = bg },
    TabLine        { fg = L2_support, bg = bg },
    TabLineFill    { fg = fg, bg = bg.da(5) },
    TabLineSel     { fg = bg, bg = L3_accent },
    Title          { fg = L3_accent, gui = "bold" },
    Visual         { bg = L3_accent.li(25) },
    VisualNOS      { bg = L3_accent.li(15) },
    WarningMsg     { fg = L3_accent, gui = "bold" },
    Whitespace     { fg = L2_support.li(20) },
    Winseparator   { fg = L2_support.li(10) },
    WildMenu       { fg = bg, bg = L3_accent },
    WinBar         { fg = fg, bg = bg },
    WinBarNC       { fg = L2_support.li(15), bg = bg },

    ------------------------------------------------------------------
    -- Syntax
    ------------------------------------------------------------------
    Comment        { fg = L2_support.li(35), gui = "italic" },
    Constant       { fg = L1_surface.li(15) },
    String         { fg = L1_surface.li(15) },
    Character      { fg = L1_surface.li(15) },
    Number         { fg = L1_surface.li(15) },
    Boolean        { fg = L1_surface.li(15) },
    Float          { fg = L1_surface.li(15) },
    Identifier     { fg = L2_support.da(10) },
    Function       { fg = L3_accent },
    Statement      { fg = L3_accent.da(5) },
    Conditional    { fg = L3_accent },
    Repeat         { fg = L3_accent.da(5) },
    Label          { fg = L4_energy },
    Operator       { fg = L2_support.li(5) },
    Keyword        { fg = L3_accent },
    Exception      { fg = L4_energy },
    PreProc        { fg = L3_accent },
    Include        { fg = L3_accent },
    Define         { fg = L3_accent },
    Macro          { fg = L3_accent },
    PreCondit      { fg = L3_accent },
    Type           { fg = L4_energy.li(5) },
    StorageClass   { fg = L4_energy },
    Structure      { fg = L4_energy },
    Typedef        { fg = L4_energy },
    Special        { fg = L2_support },
    SpecialChar    { fg = L2_support },
    Tag            { fg = L3_accent },
    Delimiter      { fg = L2_support.li(10) },
    SpecialComment { fg = L2_support.li(30) },
    Debug          { fg = L4_energy, gui = "bold" },
    Underlined     { gui = "underline" },
    Ignore         { fg = bg },
    Error          { fg = L4_energy, gui = "bold" },
    Todo           { fg = L3_accent, gui = "bold" },

    ------------------------------------------------------------------
    -- LSP / Diagnostics
    ------------------------------------------------------------------
    LspReferenceText            { bg = L3_accent.li(15) },
    LspReferenceRead            { bg = L3_accent.li(10) },
    LspReferenceWrite           { bg = L3_accent.li(5) },
    LspCodeLens                 { fg = L2_support.li(20) },
    LspCodeLensSeparator        { fg = L2_support.li(25) },
    LspSignatureActiveParameter { fg = L3_accent, gui = "bold" },

    DiagnosticError            { fg = L4_energy },
    DiagnosticWarn             { fg = L3_accent },
    DiagnosticInfo             { fg = L1_surface },
    DiagnosticHint             { fg = L2_support.li(25) },
    DiagnosticOk               { fg = L3_accent.li(15) },
    DiagnosticVirtualTextError { fg = L4_energy },
    DiagnosticVirtualTextWarn  { fg = L3_accent },
    DiagnosticVirtualTextInfo  { fg = L1_surface },
    DiagnosticVirtualTextHint  { fg = L2_support.li(25) },
    DiagnosticVirtualTextOk    { fg = L3_accent.li(15) },
    DiagnosticUnderlineError   { sp = L4_energy, gui = "undercurl" },
    DiagnosticUnderlineWarn    { sp = L3_accent, gui = "undercurl" },
    DiagnosticUnderlineInfo    { sp = L1_surface, gui = "undercurl" },
    DiagnosticUnderlineHint    { sp = L2_support.li(25), gui = "undercurl" },
    DiagnosticUnderlineOk      { sp = L3_accent.li(15), gui = "undercurl" },
    DiagnosticFloatingError    { fg = L4_energy },
    DiagnosticFloatingWarn     { fg = L3_accent },
    DiagnosticFloatingInfo     { fg = L1_surface },
    DiagnosticFloatingHint     { fg = L2_support.li(25) },
    DiagnosticFloatingOk       { fg = L3_accent.li(15) },
    DiagnosticSignError        { fg = L4_energy },
    DiagnosticSignWarn         { fg = L3_accent },
    DiagnosticSignInfo         { fg = L1_surface },
    DiagnosticSignHint         { fg = L2_support.li(25) },
    DiagnosticSignOk           { fg = L3_accent.li(15) },

    ------------------------------------------------------------------
    -- Tree-Sitter
    ------------------------------------------------------------------
    ["@text.literal"]      ={ fg = L2_support.li(25) },
    ["@text.reference"]    ={ fg = L2_support },
    ["@text.title"]        ={ fg = L3_accent, gui = "bold" },
    ["@text.uri"]          ={ fg = L3_accent, gui = "underline" },
    ["@text.underline"]    ={ fg = L3_accent, gui = "underline" },
    ["@text.todo"]         ={ fg = L3_accent, gui = "bold" },
    ["@comment"]           ={ fg = L2_support.li(35), gui = "italic" },
    ["@punctuation"]       ={ fg = L2_support.li(10) },
    ["@constant"]          ={ fg = L1_surface.li(15) },
    ["@constant.builtin"]  ={ fg = L2_support },
    ["@constant.macro"]    ={ fg = L3_accent },
    ["@define"]            ={ fg = L3_accent },
    ["@macro"]             ={ fg = L3_accent },
    ["@string"]            ={ fg = L1_surface.li(15) },
    ["@string.escape"]     ={ fg = L2_support },
    ["@string.special"]    ={ fg = L2_support },
    ["@character"]         ={ fg = L1_surface.li(15) },
    ["@character.special"] ={ fg = L2_support },
    ["@number"]            ={ fg = L1_surface.li(15) },
    ["@boolean"]           ={ fg = L1_surface.li(15) },
    ["@float"]             ={ fg = L1_surface.li(15) },
    ["@function"]          ={ fg = L3_accent },
    ["@function.builtin"]  ={ fg = L2_support },
    ["@function.macro"]    ={ fg = L3_accent },
    ["@parameter"]         ={ fg = L2_support.da(10) },
    ["@method"]            ={ fg = L3_accent },
    ["@field"]             ={ fg = L2_support.da(10) },
    ["@property"]          ={ fg = L2_support.da(10) },
    ["@constructor"]       ={ fg = L3_accent },
    ["@conditional"]       ={ fg = L3_accent },
    ["@repeat"]            ={ fg = L3_accent.da(5) },
    ["@label"]             ={ fg = L4_energy },
    ["@operator"]          ={ fg = L2_support.li(5) },
    ["@keyword"]           ={ fg = L3_accent },
    ["@exception"]         ={ fg = L4_energy },
    ["@variable"]          ={ fg = L2_support },
    ["@type"]              ={ fg = L4_energy.li(5) },
    ["@type.definition"]   ={ fg = L4_energy },
    ["@storageclass"]      ={ fg = L4_energy },
    ["@structure"]         ={ fg = L4_energy },
    ["@namespace"]         ={ fg = L2_support },
    ["@include"]           ={ fg = L3_accent },
    ["@preproc"]           ={ fg = L3_accent },
    ["@debug"]             ={ fg = L4_energy },
    ["@tag"]               ={ fg = L3_accent },

    ------------------------------------------------------------------
    -- Neo-tree
    ------------------------------------------------------------------
    NeoTreeDirectoryName { fg = L2_support },
    NeoTreeDirectoryIcon { fg = L2_support },
    NeoTreeOpenedFile     { fg = fg.da(10) },
    NeoTreeFileName       { fg = fg.da(10) },
    NeoTreeFileIcon       { fg = L2_support.li(10) },
    NeoTreeRootName       { fg = L3_accent, gui = "bold" },
    NeoTreeGitAdded       { fg = L3_accent },
    NeoTreeGitModified    { fg = L1_surface },
    NeoTreeGitDeleted     { fg = L4_energy },
  }
end)

